### ISSUE TITLE
The demo is fake? Could you release the real code to run the model

### ISSUE THREAD

**Issue by kwz219** [AutomatedProgramRepair-2021/dear-auto-fix#2]
It seems that your demo is just printing some predefined strings.
because the output_model_1 is always equal to the target data
<img width="1059" alt="90f2b7661982a7e424185af29bc79f0" src="https://user-images.githubusercontent.com/23153002/160831880-63542be2-1c83-45f2-b753-377cbe678e19.png">

Could you release the real code to run the model?

**Comment by DehengYang** [comment]
Hi @kwz219 ,
Sorry for interrupting you here. Have you successfully replicated the Dear source code?
Much appreciated if any comments could be provided.

**Comment by kwz219** [comment]
没有复现。我也是做程序修复的，咱们可以加个微信聊一下。15258971946



发自我的iPhone


------------------ Original ------------------
From: Deheng Yang ***@***.***&gt;
Date: Thu,Sep 22,2022 4:43 PM
To: AutomatedProgramRepair-2021/dear-auto-fix ***@***.***&gt;
Cc: kwz219 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [AutomatedProgramRepair-2021/dear-auto-fix] The demo is fake?Could you release the real code to run the model (Issue #2)

**Comment by nashid** [comment]
@kwz219 @DehengYang were you able run the artefact?

**Comment by kwz219** [comment]
> @kwz219 @DehengYang were you able run the artefact?
Not yet. But if you want to use some other DL-based neural program repair tools, I'm glad to recommend my repository [https://github.com/kwz219/NPR4J], which supports training and using several SOTA NPR tools such as Recoder, CoCoNut and etc...

**Comment by kwz219** [comment]
@nashid 
Not yet. But if you want to use some other DL-based program repair tools, I'm glad to recommend my repository https://github.com/kwz219/NPR4J, which supports training and using several SOTA NPR tools such as Recoder and CoCoNut, etc... We provide both raw dataset, training script and well-trained models.

**Comment by nashid** [comment]
@kwz219 your repo looks fantastic. Have you tried to run CURE?

**Comment by kwz219** [comment]
@nashid 
I tried to replicate CURE but failed. The good news is that the author of CURE released the source code https://github.com/lin-tan/CURE at last month. I haven't tried the code they released yet.
